# StrategyQA:
## Mistral

mistral7b-strategyqa:
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"

mistral7b-gsm8k:
  train: "gsm8k_static_subset_selection.csv"
  eval: "gsm8k_test_v2.csv"


mistral-strategyqa-insight:
  model: "Mistral7B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"
  eval_type: "insight"

mistral-strategyqa-exemplar:
  model: "Mistral7B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"
  eval_type: "exemplar"

mistral-strategyqa-exemplar:
  model: "Mistral7B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"
  eval_type: "insight_exemplar"

##llama3b

llama8b-strategyqa:
  model: "Llama8B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"

llama3b-strategyqa:
  model: "Llama3B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"

llama1b-strategyqa:
  model: "Llama1B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"


# GSM8K:
llama3b-gsm8k:
  model: "Llama3B"
  benchmark: "GSM8K"
  train: "gsm8k_static_subset_selection.csv"
  eval: "gsm8k_test_v2.csv"

llama1b-gsm8k:
  model: "Llama1B"
  benchmark: "GSM8K"
  train: "gsm8k_static_subset_selection.csv"
  eval: "gsm8k_test_v2.csv"


# TabMWP:
llama1b-tabmwp:
  model: "Llama1B"
  benchmark: "TabMWP"
  train: "tabmwp_static_subset_selection_mistral.csv"
  eval: "tabmwp_test.csv"