# StrategyQA:
## mistral7b
mistral7b-strategyqa:
  train: "strategyqa_train.csv"
  eval: "strategyqa_test.csv"

mistral7b-gsm8k:
  train: "gsm8k_train.csv"
  eval: "gsm8k_test.csv"

mistral7b-tabmwp:
  train: "tabmwp_train.csv"
  eval: "tabmwp_eval.csv"

mistral7b-aquarat:
  train: "aquarat_train.csv"
  eval: "aquarat_eval.csv"

mistral7b-finqa:
  train: "finqa_train.csv"
  eval: "finqa_eval.csv"

## llama3b
llama3b-strategyqa:
  train: "strategyqa_train.csv"
  eval: "strategyqa_test.csv"

llama3b-gsm8k:
  train: "gsm8k_train.csv"
  eval: "gsm8k_test.csv"

llama3b-tabmwp:
  train: "tabmwp_train.csv"
  eval: "tabmwp_eval.csv"

llama3b-aquarat:
  train: "aquarat_train.csv"
  eval: "aquarat_eval.csv"

llama3b-finqa:
  train: "finqa_train.csv"
  eval: "finqa_eval.csv"


## llama1b
llama1b-strategyqa:
  train: "strategyqa_train.csv"
  eval: "strategyqa_test.csv"

llama1b-gsm8k:
  train: "gsm8k_train.csv"
  eval: "gsm8k_test.csv"

llama1b-tabmwp:
  train: "tabmwp_train.csv"
  eval: "tabmwp_eval.csv"

llama1b-aquarat:
  train: "aquarat_train.csv"
  eval: "aquarat_eval.csv"

llama1b-finqa:
  train: "finqa_train.csv"
  eval: "finqa_eval.csv"