# StrategyQA:
mistral-strategyqa:
  model: "Mistral7B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"

llama8b-strategyqa:
  model: "Llama8B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"

llama3b-strategyqa:
  model: "Llama3B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"

llama1b-strategyqa:
  model: "Llama1B"
  benchmark: "StrategyQA"
  train: "strategyqa_static_subset_selection.csv"
  eval: "strategyqa_test.csv"


# GSM8K:
llama1b-gsm8k:
  model: "Llama1B"
  benchmark: "GSM8K"
  train: "gsm8k_static_subset_selection.csv"
  eval: "gsm8k_test_v2.csv"


# TabMWP:
llama1b-tabmwp:
  model: "Llama1B"
  benchmark: "TabMWP"
  train: "tabmwp_static_subset_selection_mistral.csv"
  eval: "tabmwp_test.csv"